name: Runs Gradle task
description: runs the provided gradle task
inputs:
  task:
    required: true
    type: string
  buildCacheProperties:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Calculate worker count
      shell: bash
      run: echo "workerCount=$(( ${{ steps.cpu-cores.outputs.count }} * 2 ))" >> $GITHUB_ENV

    - name: Decode build-cache properties
      shell: bash
      run: |
        echo -n "${{ inputs.buildCacheProperties }}" | base64 --decode > build-cache.properties

    - name: Run task
      shell: bash
      id: test
      run: |
        ./gradlew ${{ inputs.task }} \
        --no-daemon \
        --profile \
        -Dorg.gradle.daemon.idletimeout=15000 \
        -Dorg.gradle.workers.max=${{ env.workerCount }} \
        --stacktrace \
        --configuration-cache

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: build/reports
