name: Bump version
description: Bumps version name and code inside of version.properties

inputs:
  token:
    description: 'GitHub token'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Bump Version
      shell: bash
      run: |
        VERSION_FILE=version.properties

        # Get the tag name (e.g., refs/tags/v1.2.3 -> v1.2.3)
        RAW_TAG=${GITHUB_REF#refs/tags/}
        echo "Tag that triggered the workflow: $RAW_TAG"

        # Strip leading 'v' if it exists
        if [[ "$RAW_TAG" == v* ]]; then
          VERSION_NAME="${RAW_TAG:1}"
        else
          VERSION_NAME="$RAW_TAG"
        fi
        echo "Parsed VERSION_NAME: $VERSION_NAME"

        # Log the file contents before modifying
        echo "Current contents of $VERSION_FILE:"
        cat $VERSION_FILE

        # Increment VERSION_CODE by 1
        VERSION_CODE=$(grep 'VERSION_CODE=' $VERSION_FILE | cut -d '=' -f2)
        echo "Current VERSION_CODE: $VERSION_CODE"

        VERSION_CODE=$((VERSION_CODE + 1))
        echo "New VERSION_CODE: $VERSION_CODE"

        # Update the version.properties file
        sed -i "s/^VERSION_CODE=.*/VERSION_CODE=$VERSION_CODE/" $VERSION_FILE 
        sed -i "s/^VERSION_NAME=.*/VERSION_NAME=$VERSION_NAME/" $VERSION_FILE

        # Log the new contents
        echo "Updated contents of $VERSION_FILE:"
        cat $VERSION_FILE

        # Configure Git
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Set remote with authentication
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}

        # Find and checkout the default branch to avoid detached HEAD
        DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
        echo "Default branch is: $DEFAULT_BRANCH"
#        git checkout $DEFAULT_BRANCH

        # Commit and push changes
#        git add $VERSION_FILE
        git add *
        git commit -m "Bump version to $VERSION_NAME, increment VERSION_CODE to $VERSION_CODE"
        git push origin $DEFAULT_BRANCH
