name: Generate commands to generate APKs
description: generates commands to assemble based on whether the tag is a release candidate

inputs:
  non_production_tasks:
    type: string

runs:
  using: composite
  steps:
    - name: Generate tasks from tag
      shell: bash
      run: |
        # Extract the tag name (e.g., refs/tags/v1.2.3-rc1 -> v1.2.3-rc1)
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        echo "Detected tag: $TAG_NAME"

        if [[ "$TAG_NAME" == *rc* ]]; then
          echo "Tag contains 'rc' — using non-production tasks"
          TASKS="${{ inputs.non_production_tasks }}"
        else
          echo "Tag does not contain 'rc' — using generic assemble task"
          TASKS="assemble"
        fi

        echo "Final Gradle Tasks: $TASKS"
        echo "TASKS=$TASKS" >> $GITHUB_ENV
