name: Generate commands to generate APKs
description: generates commands to assemble based on product flavours and build types from the release name

runs:
  using: composite
  steps:
    - name: Generate commands to generate APKs
      run: |
        RELEASE_NAME="${{ github.event.release.name }}"
        
        # Split release name into components
        IFS=' | ' read -r VERSION PRODUCT_FLAVORS BUILD_TYPES <<< "$RELEASE_NAME"
        
        echo "Extracted Version: $VERSION"
        echo "Extracted Product Flavours: $PRODUCT_FLAVORS"
        echo "Extracted Build Types: $BUILD_TYPES"
        
        TASKS=""
        for FLAVOR in $(echo "$PRODUCT_FLAVORS" | tr ',' ' '); do
          for TYPE in $(echo "$BUILD_TYPES" | tr ',' ' '); do
            TASK_NAME="assemble$(echo $FLAVOR | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')$(echo $TYPE | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
            TASKS="$TASKS $TASK_NAME"
          done
        done
        
        echo "Generated Gradle Tasks: $TASKS"
        echo "TASKS=$TASKS" >> $GITHUB_ENV

      shell: bash