name: Generates github.properties
description: generate github.properties file
inputs:
  token:
    description: 'Github token'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Generate github.properties
      shell: bash
      run: |
        echo -e "github.username=\SoninApps\ngithub.password=\${{ inputs.token }}\ngithub.repo.name=GithubPackages\ngithub.repo.url=https://maven.pkg.github.com/SoninApps/android-component-library" > github.properties
        
        echo "Contents of github.properties:"
        cat github.properties
