name: Generates github.properties
description: generate github.properties file
inputs:
  token:
    description: 'Github token'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Generate github.properties in $HOME/.sonin
      shell: bash
      run: |
        mkdir -p "$HOME/.sonin"
        echo -e "github.username=SoninApps\ngithub.password=${{ inputs.token }}\ngithub.repo.name=GithubPackages\ngithub.repo.url=https://maven.pkg.github.com/SoninApps/android-component-library" > "$HOME/.sonin/github-credentials.properties"