name: Deployment

on:
  push:
    tags:
      - 'v*'  # matches tags like v1.2.3-rc1
      - '[0-9]*'  # matches tags like 1.2.3

jobs:
  deploy:
    uses: AleksejB/notes-in-ddd-and-tests/.github/workflows/build-apks-trigger-manual-v1.yml@master
    with:
      tasks:
        "assembleStagingRelease, assembleUatRelease"
      files: | 
        map.properties=MAPS_API_KEY=asdasd
