name: Create Staging Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release (e.g., 1.2.3-rc1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Step 1: Bump Version
      - name: Bump Version
        run: |
          VERSION_FILE=version.properties
          # Increment VERSION_CODE by 1
          VERSION_CODE=$(grep -oP 'VERSION_CODE=\K\d+' $VERSION_FILE)
          VERSION_CODE=$((VERSION_CODE + 1))

          # Set VERSION_NAME to the supplied version
          VERSION_NAME=${{ inputs.version }}

          # Update the version.properties file
          sed -i "s/^VERSION_CODE=\d\+/VERSION_CODE=$VERSION_CODE/" $VERSION_FILE
          sed -i "s/^VERSION_NAME=.*/VERSION_NAME=$VERSION_NAME/" $VERSION_FILE

          # Commit and push changes to version.properties
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $VERSION_FILE
          git commit -m "Bump version to $VERSION_NAME, increment VERSION_CODE to $VERSION_CODE"
          git push origin HEAD

#      # Step 2: Create GitHub Release with Tag and Name = Version
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ inputs.version }}
#          name: Release ${{ inputs.version }}
#          body: |
#            ## Changes
#            - Describe the changes in this release.
#          draft: false
#          prerelease: true
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      # Step 3: Build APKs
#      - name: Build APKs
#        run: ./gradlew yourCustomTaskName
#
#      # Step 4: Attach APKs to the Release
#      - name: Upload APKs to Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ inputs.version }}
#          files: |
#            app/build/outputs/apk/**/*.apk
#          token: ${{ secrets.GITHUB_TOKEN }}
